version: "3.1"
services:
   lokale-partijen:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/opt/lp
    networks:
      - lp
      - nginx-load-balancer
    restart: always
networks:
  lp:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
